// Generated by CoffeeScript 1.3.3

/*!
 * Copyright (c) 2012 Andrew Volkov <hello@vol4ok.net>
*/


(function() {
  var $, cache, ck, hogan, read, render,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $ = {};

  __extends($, require('path'));

  __extends($, require('fs'));

  __extends($, require('util'));

  hogan = require('hogan.js');

  ck = require('./coffeekup');

  cache = {};

  read = function(path, options, fn) {
    var ckExt, str, _ref;
    ckExt = (_ref = options.ck) != null ? _ref : '.ck';
    str = cache[path];
    if (options.cache && str) {
      return fn(null, str);
    }
    return $.readFile(path, 'utf8', function(err, str) {
      if (err) {
        return fn(err);
      }
      if ($.extname(path) === ckExt) {
        str = ck.render(str);
      }
      if (options.cache) {
        cache[path] = str;
      }
      return fn(null, str);
    });
  };

  render = function(path, opt, fn) {
    if (typeof opt === "function") {
      fn = opt;
      opt = {};
    }
    if (opt.asString == null) {
      opt.asString = true;
    }
    return read(path, opt, function(err, str) {
      var result;
      if (err) {
        return fn(err);
      }
      try {
        result = hogan.compile(str, opt);
        return fn(null, result);
      } catch (err) {
        return fn(err);
      }
    });
  };

  module.exports = render;

}).call(this);
